package org.acme.utils.enums;

public enum EducationLevel {
    COMPLETE_HIGH_SCHOOL,
    COMPLETE_TECHNICAL,
    INCOMPLETE_HIGHER_SCHOOL,
    COMPLETE_HIGHER_SCHOOL,
    COMPLETE_TECHNOLOGY,
    COMPLETE_POSTGRADUATE,
    COMPLETE_MASTERS,
    COMPLETE_DOCTORATE,
    COMPLETE_MBA,
}