package org.acme.utils.enums;

public enum EducationLevel {
    MEDIO_COMPLETO,
    TECNICO_COMPLETO,
    SUPERIOR_INCOMPLETO,
    SUPERIOR_COMPLETO,
    TECNOLOGO_COMPLETO,
    POS_GRADUACAO_COMPLETO,
    MESTRADO_COMPLETO,
    DOUTORADO_COMPLETO,
    MBA_COMPLETO,
}